version: 2.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/CircleCI-101
    steps:
      - checkout
      - run: ls -al
  test:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/CircleCI-101
    steps:
      - checkout
      - run: echo "test"


  deploy:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/CircleCI-101
    environment:
      BRANCH: "master"
    steps:
      - checkout
      - run:
          command: |
            sleep 5 # sleep for 5 seconds to wait for dynos
            echo "deploy if branch on ${BRANCH}"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test:
          filters:
            branches:
              only: develop
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master